/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package huffman;

public class App {
    public static void main(String[] args) {
        Node tree = TreeCreator.create("Hello World βδασψ⊂Γℝ∅ΦΔ");
        String serial = tree.serialize();
        System.out.println(serial);
        Node tree2 = Serialize.deserialize(serial);
        System.out.println(tree.equals(tree2));
    }
}
